language: ruby
sudo: false

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - jruby-9.1.7.0

env:
 - PARSE_HOST=https://parse-ruby-client-server.herokuapp.com PARSE_HOST_PATH=/parse PARSE_APPLICATION_ID=80b8063a0acd16236ea8 PARSE_MASTER_API_KEY=cf9a0738b2687973f7b8
